#+title: Lispiano
#+author: Grolter Bell
#+email: varedif.a.s@gmail.com
#+description: Piano for your keyboard written in CL
#+language: en

* Depends on
** sketch
   Uses ~define-start-function~ feature that is available in the
   ~define-start-function-2~ branch of my [[https://github.com/Gleefre/sketch/tree/define-start-function-2][fork]] of the library.
   You can clone it with
   #+BEGIN_SRC bash
   git clone -b define-start-function-2 https://github.com/Gleefre/sketch
   #+END_SRC
   See the original [[https://github.com/vydd/sketch][github repo]] for more information on sketch requirements.
** sketch-fit
   Little utility: [[https://github.com/Gleefre/sketch-fit][github repo]]. Needs to be cloned to your local-projects folder:
   #+BEGIN_SRC bash
   git clone https://github.com/Gleefre/sketch-fit
   #+END_SRC
** sdl2-mixer
   See [[https://github.com/lispgames/cl-sdl2-mixer][github repo]].
** Foreign dependencies
*** SDL2
    See [[https://www.libsdl.org/][libsdl website]].
*** SDL2 Image & SDL2 TTF & SDL2 Mixer
    These are parts of SDL2 project needed by lispiano.
* Installation
  You need to clone this repository to your local-projects folder:
   #+BEGIN_SRC bash
   git clone https://github.com/Gleefre/lispiano
   #+END_SRC
* Usage
  Load the system:
  #+BEGIN_SRC lisp
  (ql:quickload :lispiano)
  ; or with asdf
  (asdf:load-system :lispiano)
  #+END_SRC
* todo list
** TODO Generate notes from scratch/one note instead of using predefined files for each one.
** TODO Add different keyboard layouts.
** TODO Creating user map for notes on a keyboard.
